version: '3'

services:
  node1:
    image: funkypenguin/NinjaCoin
    container_name: ninjatest-node1
    volumes:
      - ../NinjaCoind:/var/lib/NinjaCoind/
    networks:
      testnet:
        ipv4_address: 172.16.76.11
  
#  node2:
#    image: funkypenguin/NinjaCoin
#    container_name: ninjatest-node2
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.12
  
#  node3:
#    image: funkypenguin/NinjaCoin
#    container_name: ninjatest-node3
#    networks:
#      testnet:
#        ipv4_address: 172.16.76.13

networks:
  testnet:
    ipam:
      config:
        - subnet: 172.16.76.0/24

